[tox]
envlist = py39
isolated_build = true

[testenv]
deps =
    pytest
    pytest-cov
commands =
    python -m pytest tests -v

[testenv:lint]
deps =
    ruff
commands =
    ruff check .
    ruff format --check .
