[tox]
envlist = py39
isolated_build = true

[testenv]
deps =
    pytest
    pytest-cov
commands =
    python -m pytest tests -v

[testenv:lint]
deps =
    black
    isort
    flake8
commands =
    black --check .
    isort --check-only .
    flake8 .
